# Use 'docker-compose build' or 'docker-compose up --build' to rebuild images
version: '3.5'
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - '8000:8000'
  frontend:
    build:
      context: ./packages/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
